require: rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - /**/spec/spec_helper.rb

Style/FrozenStringLiteralComment: 
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

